version: '3.8'

services:
  db-pagos:
    image: mysql:8.0
    container_name: mysql-pagos-container
    environment:
      MYSQL_ROOT_PASSWORD: system
      MYSQL_DATABASE: db_pagos
    ports:
      - "3307:3306"
    volumes:
      - mysql_pagos_data:/var/lib/mysql

volumes:
  mysql_pagos_data: