spring.profiles.active=dev

# 🧭 RUTAS PERSONALIZADAS DE SWAGGER (VÍA GATEWAY)
springdoc.swagger-ui.path=/api/v1/pagos/doc/swagger-ui.html
springdoc.api-docs.path=/api/v1/pagos/v3/api-docs

# 🌐 REDIRECCIÓN AL API GATEWAY
springdoc.openapi.servers[0].url=http://localhost:8080
springdoc.openapi.servers[0].description=API Gateway (Entorno Local)